# Generated by Django 2.2.10 on 2020-08-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='session_id',
            new_name='player_session',
        ),
    ]
