# Generated by Django 2.2.10 on 2020-09-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='player_attempts',
            field=models.IntegerField(default=None, null=True, verbose_name='Количество попыток'),
        ),
    ]
