# Generated by Django 2.2.10 on 2020-08-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_player_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_number',
        ),
    ]
