# Generated by Django 2.2.10 on 2020-09-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200903_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='attempts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_game_attempts', to='game.Player'),
        ),
    ]
